### ISSUE TITLE
Using buttons with multiple encoders

### ISSUE THREAD

**Issue by guibom** [0xPIT/encoder#2] opened 2014-08-10 23:50 UTC
I was having issues using multiple encoder objects with their buttons.

Only the first object that runs the service function would update their value.
The actual encoder part of the object runs fine and keeps their individual positions.

My solution (not sure if ideal) was to remove the static variables keyDownTicks, doubleClickTicks, lastButtonCheck from the service function and move them to the header file.

**Comment by samkusnetz** [comment] 2015-03-29 19:35
guibom, where did you move them to, exactly? i'm trying the same solution and still cannot get my second and third encoders' buttons to register.

**Comment by Ardego** [comment] 2015-07-21 20:28
Hi,
I just stumbled over the same issue, want to use two encoders with buttons,
Number 1 works flawlessly, but number two ignores all button activity for some reason.
Grateful for any help into the right direction.

Thanks!

**Comment by mr-miky** [comment] 2015-09-22 23:19
has a fucking bugs in the service () !!

technically the reading of the second button is not executed because occurs during the period of debouncing of the previous button.
The problem arises because keyDownTicks, doubleClickTicks, lastButtonCheck are static.
I solved by making sure that every instance of "ClickEncoder" have their keyDownTicks, doubleClickTicks, lastButtonCheck.

The changes are small to do ....

**Comment by mr-miky** [comment] 2015-09-22 23:40
in clickEncoder.h  add  keyDownTicks, doubleClickTicks, lastButtonCheck:

#ifndef WITHOUT_BUTTON
  volatile Button button;
  bool doubleClickEnabled;
  bool accelerationEnabled;
  uint16_t keyDownTicks;
  uint8_t doubleClickTicks;
  unsigned long lastButtonCheck;
#endif

in ClickEncoder.cpp  initialize keyDownTicks, doubleClickTicks, lastButtonCheck

if (digitalRead(pinA) == pinsActive) {
    last = 3;
  }

  if (digitalRead(pinB) == pinsActive) {
    last ^=1;
  }

#ifndef WITHOUT_BUTTON
  keyDownTicks = 0;
  doubleClickTicks = 0;
  lastButtonCheck = 0;
#endif

and comment all 3 line with static declaration

  // handle button
  //
#ifndef WITHOUT_BUTTON
//  static uint16_t keyDownTicks = 0;
//  static uint8_t doubleClickTicks = 0;
//  static unsigned long lastButtonCheck = 0;

**Comment by noxx2015** [comment] 2015-11-19 18:20
i try your code, but my second encoder will not run, i dont no why....

here is my code:

#include <TimerThree.h>
#include <Keyboard.h>
#include <ClickEncoder.h>
#include <TimerOne.h>


ClickEncoder *encoder01;
ClickEncoder *encoder02;

int16_t last01, value01;
int16_t last02, value02;

void timerIsr01() 
{
  encoder01->service();
}

void timerIsr02() 
{
  encoder02->service();
}

void setup() 
{
  Serial.begin(9600);
  encoder01 = new ClickEncoder(A1, A0, A2, 4);  // Encoder Pin an A0 und A1, Button Pin an A2; Restlichen Pins direkt an GND ### 4 = stepsPerNotch
  encoder02 = new ClickEncoder(A4, A3, A5, 4);  // Encoder Pin an A0 und A1, Button Pin an A2; Restlichen Pins direkt an GND ### 4 = stepsPerNotch


  Timer1.initialize(1000);
  Timer1.attachInterrupt(timerIsr01); 
  
  Timer3.initialize(1000);  
  Timer3.attachInterrupt(timerIsr02);
  
  last01 = -1;
  last02 = -1;
}

void loop() 
{  
  value01 += encoder01->getValue();
  
  if (value01 != last01) 
  {
    if (value01 < last01)
    {
      Serial.print(value01);
      Serial.print("\n01: Right \n");
 
    }
    if (value01 > last01)
    {
      Serial.print(value01);
      Serial.print("\n01: Left \n");

    }
    last01 = value01;
  }
  
  ClickEncoder::Button b = encoder01->getButton();
  if (b != ClickEncoder::Open) 
  {
    switch (b) 
    {
      case ClickEncoder::Pressed:
        Serial.print("01: Pressed \n");
        break;
      case ClickEncoder::Held:
        Serial.print("01: Held \n");
        break;
      case ClickEncoder::Released:
        Serial.print("01: Released \n");
        break;
      case ClickEncoder::Clicked:
        Serial.print("01: Clicked \n");
        break;
      case ClickEncoder::DoubleClicked:
        Serial.print("01: DoubleClicked \n");
        break;
    }

  // E N C O D E R 2

  value02 += encoder02->getValue();
  
  if (value02 != last02) 
  {
    if (value02 < last02)
    {
      Serial.print(value02);
      Serial.print("\n01: Right \n");
 
    }
    if (value02 > last02)
    {
      Serial.print(value02);
      Serial.print("\n02: Left \n");

    }
    last02 = value02;
  }
  
  ClickEncoder::Button c = encoder02->getButton();
  if (c != ClickEncoder::Open) 
  {
    switch (c) 
    {
      case ClickEncoder::Pressed:
        Serial.print("02: Pressed \n");
        break;
      case ClickEncoder::Held:
        Serial.print("02: Held \n");
        break;
      case ClickEncoder::Released:
        Serial.print("02: Released \n");
        break;
      case ClickEncoder::Clicked:
        Serial.print("02: Clicked \n");
        break;
      case ClickEncoder::DoubleClicked:
        Serial.print("02: DoubleClicked \n");
        break;
    }
  }
      
  }    
}

**Comment by mr-miky** [comment] 2015-11-19 20:22
I suspect the problem is that you use 2 timers.
It makes no sense, so try:

void timerIsr01()
{
encoder01->service();
encoder02->service();
}

and remove the code for timer3 ( initialization etc etc )

**Comment by noxx2015** [comment] 2015-11-20 20:31
i change the code, but it will not work
encoder 1 works fine, encoder 2 do nothing

my ClickEncoder.h:
http://pastebin.com/JYVd1jVt

my ClickEncoder.cpp:
http://pastebin.com/mybzDgDd

myCode:

#include <Keyboard.h>
#include <ClickEncoder.h>
#include <TimerOne.h>


ClickEncoder *encoder01;
ClickEncoder *encoder02;

int16_t last01, value01;
int16_t last02, value02;

void timerIsr01() 
{
  encoder01->service();
  encoder02->service();
}


void setup() 
{
  Serial.begin(9600);
  encoder01 = new ClickEncoder(A1, A0, A2, 4);  // Encoder Pin an A0 und A1, Button Pin an A2; Restlichen Pins direkt an GND ### 4 = stepsPerNotch
  encoder02 = new ClickEncoder(A4, A3, A5, 4);  // Encoder Pin an A0 und A1, Button Pin an A2; Restlichen Pins direkt an GND ### 4 = stepsPerNotch


  Timer1.initialize(1000);
  Timer1.attachInterrupt(timerIsr01); 
  
  
  last01 = -1;
  last02 = -1;
}

void loop() 
{  
  value01 += encoder01->getValue();
  
  if (value01 != last01) 
  {
    if (value01 < last01)
    {
      Serial.print(value01);
      Serial.print("\n01: Right \n");
 
    }
    if (value01 > last01)
    {
      Serial.print(value01);
      Serial.print("\n01: Left \n");

    }
    last01 = value01;
  }
  
  ClickEncoder::Button b = encoder01->getButton();
  if (b != ClickEncoder::Open) 
  {
    switch (b) 
    {
      case ClickEncoder::Pressed:
        Serial.print("01: Pressed \n");
        break;
      case ClickEncoder::Held:
        Serial.print("01: Held \n");
        break;
      case ClickEncoder::Released:
        Serial.print("01: Released \n");
        break;
      case ClickEncoder::Clicked:
        Serial.print("01: Clicked \n");
        break;
      case ClickEncoder::DoubleClicked:
        Serial.print("01: DoubleClicked \n");
        break;
    }

  // E N C O D E R 2

  value02 += encoder02->getValue();
  
  if (value02 != last02) 
  {
    if (value02 < last02)
    {
      Serial.print(value02);
      Serial.print("\n01: Right \n");
 
    }
    if (value02 > last02)
    {
      Serial.print(value02);
      Serial.print("\n02: Left \n");

    }
    last02 = value02;
  }
  
  ClickEncoder::Button c = encoder02->getButton();
  if (c != ClickEncoder::Open) 
  {
    switch (c) 
    {
      case ClickEncoder::Pressed:
        Serial.print("02: Pressed \n");
        break;
      case ClickEncoder::Held:
        Serial.print("02: Held \n");
        break;
      case ClickEncoder::Released:
        Serial.print("02: Released \n");
        break;
      case ClickEncoder::Clicked:
        Serial.print("02: Clicked \n");
        break;
      case ClickEncoder::DoubleClicked:
        Serial.print("02: DoubleClicked \n");
        break;
    }
  }
      
  }    
}

**Comment by mr-miky** [comment] 2015-11-21 00:05
try to swap encoder service

void timerIsr01()
{
encoder02->service();
encoder01->service();
}

in my case, when I did so, the push button 2 worked but not more than the 1

can you confirm ?

**Comment by noxx2015** [comment] 2015-11-21 06:22
no, if i change to
void timerIsr01()
{
encoder02->service();
encoder01->service();
}
also encoder 1 works, encoder 2 not

**Comment by mr-miky** [comment] 2015-11-21 10:35
try to swap connections of encoders. 
making the exchange you can understand if the button of encoder 2 really works or if the input of Arduino used for the push button 2 is faulty.

I can manage 6 multiplexed encoders ....

**Comment by noxx2015** [comment] 2015-11-21 12:00
Both Encoder works. Change to other Pins dont works, i mean only one works.

Can you post your *.h and *.cpp and your arduino code? Pastebin?

**Comment by noxx2015** [comment] 2015-11-21 20:42
i ve now a solution.
i copy the complete libary to a second folder Clickencoder2
and change all Clickencoder to Clickencoder2 (in *.h and *.cpp)
in my scetch i use this
ClickEncoder *encoder;
ClickEncoder2 *encoder2;

works

**Comment by mr-miky** [comment] 2015-11-21 22:33
But ... i've found the reason why encoder2 don't work !
Your code is syntactically correct but wrong. 
I copied and pasted your code on a C ++ editor, and then I did indent reformat.

your code
http://pastebin.com/zR5UTjxU

my fixed & tested code
http://pastebin.com/KaUUF7ZC

see the higligted difference ...

**Comment by noxx2015** [comment] 2015-11-22 07:07
hmm. thx. but i see no diffence ?!?!?!

**Comment by mr-miky** [comment] 2015-11-22 11:58
wow ... no difference ?
in your code all the instructions for the second encoder are performed only when the button of the first encoder is not open .....

The only difference between the two codes is where are located 2 braces.

I do not remember if the arduino IDE has highlighting matching bracket. Moving the cursor after an open bracket it highlight the corresponding closing bracket

**Comment by soligen2010** [comment] 2016-02-19 13:53
I have resolved this issue some others as well in my fork here: [https://github.com/soligen2010/encoder](https://github.com/soligen2010/encoder)  Example program below.

I have also fixed a problem causing randomly lost events, and disabling double clicks now works properly.  There is still some other things I want to do, but please give  my fork a try. 

example:

#include <ClickEncoder.h>
#include <TimerOne.h>

ClickEncoder encoder = ClickEncoder(8, 8, 8);
ClickEncoder encoder2 = ClickEncoder(7, 7, 7);
int16_t last, value;

void timerIsr() {
  encoder.service();
  encoder2.service();
}

void setup() {
  Serial.begin(115200);
//  encoder = new ClickEncoder(8, 8, 8);

  Timer1.initialize(1000);
  Timer1.attachInterrupt(timerIsr); 
  encoder.setButtonHeldEnabled(true);
  encoder.setDoubleClickEnabled(true);

}

void loop() {  
  
  ClickEncoder::Button b = encoder.getButton();
  if (b != ClickEncoder::Open) {
    Serial.print("Button: ");
    #define VERBOSECASE(label) case label: Serial.println(#label); break;
    switch (b) {
      VERBOSECASE(ClickEncoder::Pressed);
      VERBOSECASE(ClickEncoder::Held)
      VERBOSECASE(ClickEncoder::Released)
      VERBOSECASE(ClickEncoder::Clicked)
      VERBOSECASE(ClickEncoder::DoubleClicked)
    }
  }    
  
  ClickEncoder::Button b2 = encoder2.getButton();
  if (b2 != ClickEncoder::Open) {
    Serial.print("Button2: ");
    #define VERBOSECASE(label) case label: Serial.println(#label); break;
    switch (b2) {
      VERBOSECASE(ClickEncoder::Pressed);
      VERBOSECASE(ClickEncoder::Held)
      VERBOSECASE(ClickEncoder::Released)
      VERBOSECASE(ClickEncoder::Clicked)
      VERBOSECASE(ClickEncoder::DoubleClicked)
    }
  }    
}

**Comment by callimero** [comment] 2016-04-01 20:51
@soligen2010 Thanks! I tried the whole day fixing the original code with my certainly limited knowledge. I was on the right spot but just using your fork saved me many more hours i guess :-)

Two Encoders and Buttons work now.

**Comment by soligen2010** [comment] 2016-04-03 01:29
Cool, I'm glad it helped

**Comment by daydreamerZzz** [comment] 2017-04-28 02:03
@soligen2010 Thanks so much!! I am doing a project involving multiple click encoders. I know something was wrong with the code but couldn't solve it b/c I have never coded in c++ before. you saved my life!

**Comment by soligen2010** [comment] 2017-04-28 11:52
You are welcome. I am glad you found it useful

**Closed** 2017-05-02 20:08 UTC
